Sylius\Component\Core\Model\ShopUser:
    properties:
        username:
            faker: email
            unique: true
            prefix: 'anonymized-'
        usernameCanonical:
            faker: email
            unique: true
            prefix: 'anonymized-'
        password:
            faker: sha256
            prefix: 'anonymized-'
        lastLogin:
            faker: dateTimeBetween
            args: ['+100 years', '+101 years']
        emailVerificationToken:
            value: null
        passwordResetToken:
            value: null
        passwordRequestedAt:
            faker: dateTime
        verifiedAt:
            faker: dateTime
        email:
            faker: email
            unique: true
        emailCanonical:
            faker: email
            unique: true
